//! Golden tests against the *official* whisper implementation, one case per
//! model.
//!
//! The goldens in docs/golden/ are not hand-written: they are whatever
//! openai/whisper produces for test_16000_mono.wav, regenerated by
//! `scripts/cement_reference.py` and accompanied by a `.provenance.json`
//! recording the library version, the search settings and the audio. That
//! provenance is what makes a golden auditable rather than folklore.
//!
//! # Why the gate is layered
//!
//! Exact equality is achievable, and we hold it where it matters most: on
//! large-v3 transcribing Hebrew - the model and language people actually use.
//! Across the other models we are close but not identical, and the pattern is
//! explainable rather than alarming. Our arithmetic is not PyTorch's (burn on
//! f32 vs PyTorch on f32), so where two tokens are nearly tied, a difference
//! in the last decimal place flips the winner. A 1.55B-parameter model is
//! confident and agrees exactly; `tiny` barely decides and drifts.
//!
//! So the gate is:
//!
//! 1. **Exact** - large-v3 in Hebrew must match the reference character for
//!    character. Any real regression in decoding fails here.
//! 2. **Structural** - every model must detect the language correctly and land
//!    within one segment of the reference.
//! 3. **Text similarity** - transcripts in the spoken language must be within
//!    10% edit distance of the reference.
//! 4. **Recorded only** - forcing English on Hebrew audio is excluded from
//!    assertions. The task is degenerate by design and both implementations
//!    emit different nonsense; a check there would measure luck, not quality.
//!
//! # Running
//!
//! Every model is downloaded on first use, so this is opt-in and slow:
//!
//! ```text
//! cargo test -p whisper-burn-cli --test golden_models -- --ignored
//! ```
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::{Mutex, OnceLock};

const EXE: &str = env!("CARGO_BIN_EXE_whisper-burn-cli");

/// Search settings the goldens were generated with. They must match
/// `scripts/cement_reference.py`, or the comparison is between two different
/// algorithms.
const BEAM_SIZE: &str = "5";

/// How strictly a configuration must match its golden.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Gate {
    /// Byte-for-byte equality with the reference.
    Exact,
    /// Correct language, within one segment, text within [`TEXT_TOLERANCE`].
    Structural,
    /// Compared and reported, but never asserted on. Degenerate by design.
    RecordedOnly,
}

struct Case {
    model: &'static str,
    /// `None` means "let the reference and we both auto-detect".
    language: Option<&'static str>,
    gate: Gate,
}

/// Transcripts in the spoken language may differ by at most this fraction of
/// characters. Measured worst case across the eight native-language cases is
/// 9 characters on a 157-character transcript (tiny, 5.7%); large-v3 is 0.
const TEXT_TOLERANCE: f64 = 0.10;

/// Segment counts may differ by at most this much. Only large-v2 currently
/// differs, by one (we emit 2, the reference emits 3).
const SEGMENT_SLACK: usize = 1;

const CASES: &[Case] = &[
    // The flagship: exact, byte for byte, in the language actually spoken.
    Case { model: "large-v3", language: None, gate: Gate::Exact },
    Case { model: "large-v3", language: Some("he"), gate: Gate::Exact },
    // The rest of the size range: correct language, near-identical transcript.
    Case { model: "tiny", language: None, gate: Gate::Structural },
    Case { model: "base", language: None, gate: Gate::Structural },
    Case { model: "small", language: None, gate: Gate::Structural },
    Case { model: "medium", language: None, gate: Gate::Structural },
    Case { model: "large", language: None, gate: Gate::Structural },
    Case { model: "large-v2", language: None, gate: Gate::Structural },
    Case { model: "large-v3-turbo", language: None, gate: Gate::Structural },
    // Forced native language on the weakest model.
    Case { model: "tiny", language: Some("he"), gate: Gate::Structural },
    // Degenerate: English output forced onto Hebrew audio. Recorded, not gated.
    Case { model: "tiny", language: Some("en"), gate: Gate::RecordedOnly },
    Case { model: "large-v3", language: Some("en"), gate: Gate::RecordedOnly },
];

fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/golden")
}

fn golden_path(case: &Case) -> PathBuf {
    let suffix = case.language.unwrap_or("auto");
    golden_dir().join(format!("reference_{}_{suffix}_golden.json", case.model))
}

fn label(case: &Case) -> String {
    match case.language {
        Some(language) => format!("{}/{}", case.model, language),
        None => format!("{}/auto", case.model),
    }
}

/// Copy the clip somewhere writable: `--output json` writes its sidecar next
/// to the input, and the goldens must not litter the repository.
///
/// The name is unique per case. The tiers run concurrently and each decodes
/// several models, so a shared filename turns into a file-lock race - and a
/// half-written sidecar reads as a wildly wrong transcript rather than as the
/// collision it is.
fn clip_in_temp_dir(case: &Case) -> PathBuf {
    let key = label(case).replace('/', "-");
    let dir = std::env::temp_dir().join("whisper_burn_golden_models");
    std::fs::create_dir_all(&dir).expect("temp dir");
    let wav = dir.join(format!("{key}.wav"));
    std::fs::copy(
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../../test_16000_mono.wav"),
        &wav,
    )
    .expect("copy the golden clip");
    wav
}

/// Decodes are expensive and the tiers all need the same ones, so each
/// (model, language) pair is decoded at most once per test binary.
fn decoded(case: &Case) -> serde_json::Value {
    static CACHE: OnceLock<Mutex<HashMap<String, serde_json::Value>>> = OnceLock::new();
    let cache = CACHE.get_or_init(|| Mutex::new(HashMap::new()));
    let key = label(case);

    if let Some(hit) = cache.lock().unwrap().get(&key) {
        return hit.clone();
    }

    let wav = clip_in_temp_dir(case);
    let mut command = Command::new(EXE);
    command
        .arg(&wav)
        .args(["--model", case.model, "--beam-size", BEAM_SIZE])
        .args(["--output", "json"]);
    if let Some(language) = case.language {
        command.args(["--language", language]);
    }
    let out = command.output().expect("run the cli");
    assert!(
        out.status.success(),
        "cli failed for {key}: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    // `--output json` writes a file; stdout carries human-readable bracket
    // lines, not the transcript.
    let sidecar = wav.with_extension("json");
    let ours: serde_json::Value = serde_json::from_slice(
        &std::fs::read(&sidecar).unwrap_or_else(|e| panic!("read {}: {e}", sidecar.display())),
    )
    .expect("sidecar json parses");

    cache.lock().unwrap().insert(key, ours.clone());
    ours
}

fn golden(case: &Case) -> serde_json::Value {
    let path = golden_path(case);
    let raw = std::fs::read(&path)
        .unwrap_or_else(|e| panic!("read golden {}: {e}", path.display()));
    serde_json::from_slice(&raw)
        .unwrap_or_else(|e| panic!("parse golden {}: {e}", path.display()))
}

fn segments(value: &serde_json::Value) -> &[serde_json::Value] {
    value["segments"].as_array().expect("segments is an array")
}

fn joined_text(value: &serde_json::Value) -> String {
    segments(value)
        .iter()
        .map(|segment| segment["text"].as_str().unwrap_or_default().to_string())
        .collect()
}

/// Levenshtein distance, for the similarity tier. Transcripts here are a few
/// hundred characters, so the quadratic table is free.
fn edit_distance(a: &str, b: &str) -> usize {
    let a: Vec<char> = a.chars().collect();
    let b: Vec<char> = b.chars().collect();
    if a.is_empty() {
        return b.len();
    }
    if b.is_empty() {
        return a.len();
    }
    let mut previous: Vec<usize> = (0..=b.len()).collect();
    let mut current = vec![0usize; b.len() + 1];
    for (i, ca) in a.iter().enumerate() {
        current[0] = i + 1;
        for (j, cb) in b.iter().enumerate() {
            // substitution (diagonal), deletion, then insertion.
            let substitution = previous[j] + usize::from(ca != cb);
            let deletion = previous[j + 1] + 1;
            let insertion = current[j] + 1;
            current[j + 1] = substitution.min(deletion).min(insertion);
        }
        std::mem::swap(&mut previous, &mut current);
    }
    previous[b.len()]
}

/// The similarity tier is only as trustworthy as its metric, and a wrong
/// distance here either hides a regression or fails a healthy build.
#[test]
fn edit_distance_is_levenshtein() {
    assert_eq!(edit_distance("", ""), 0);
    assert_eq!(edit_distance("abc", "abc"), 0);
    assert_eq!(edit_distance("abc", ""), 3);
    assert_eq!(edit_distance("", "abc"), 3);
    assert_eq!(edit_distance("abc", "abd"), 1);
    assert_eq!(edit_distance("abd", "abc"), 1);
    assert_eq!(edit_distance("flaw", "lawn"), 2);
    assert_eq!(edit_distance("kitten", "sitting"), 3);
    assert_eq!(edit_distance("sitting", "kitten"), 3);
    // A single inserted character must cost exactly one, not one per row.
    let base = "a".repeat(200);
    assert_eq!(edit_distance(&base, &format!("{base}b")), 1);
    // Distance can never exceed the length of the longer string.
    for (x, y) in [("abcdef", "uvwxyz"), (&base, "b"), ("", &base)] {
        assert!(
            edit_distance(x, y) <= x.chars().count().max(y.chars().count()),
            "edit_distance({x:?}, {y:?}) exceeded the longest input"
        );
    }
}

fn check_structure(case: &Case, ours: &serde_json::Value, reference: &serde_json::Value) {
    let name = label(case);
    assert_eq!(
        ours["language"], reference["language"],
        "{name}: detected language differs from the reference"
    );

    let ours_len = segments(ours).len();
    let reference_len = segments(reference).len();
    assert!(
        ours_len.abs_diff(reference_len) <= SEGMENT_SLACK,
        "{name}: segment count ours={ours_len} reference={reference_len} (slack {SEGMENT_SLACK})"
    );

    let ours_text = joined_text(ours);
    let reference_text = joined_text(reference);
    let distance = edit_distance(&ours_text, &reference_text);
    let longest = ours_text.chars().count().max(reference_text.chars().count()).max(1);
    let ratio = distance as f64 / longest as f64;
    assert!(
        ratio <= TEXT_TOLERANCE,
        "{name}: transcript differs by {distance} of {longest} chars ({:.1}%, tolerance {:.0}%)",
        ratio * 100.0,
        TEXT_TOLERANCE * 100.0
    );
}

/// Tier 1: the flagship must be identical, character for character.
#[test]
#[ignore = "heavy: downloads model weights and runs every model (~10 min first time)"]
fn large_v3_hebrew_matches_the_reference_exactly() {
    for case in CASES.iter().filter(|case| case.gate == Gate::Exact) {
        let ours = decoded(case);
        let reference = golden(case);
        assert_eq!(
            ours,
            reference,
            "{}: no longer matches the reference whisper output exactly",
            label(case)
        );
    }
}

/// Tiers 2 and 3: every model gets the language right and stays close.
#[test]
#[ignore = "heavy: downloads model weights and runs every model (~10 min first time)"]
fn every_model_tracks_the_reference() {
    for case in CASES.iter().filter(|case| case.gate == Gate::Structural) {
        check_structure(case, &decoded(case), &golden(case));
    }
}

/// Tier 4: the degenerate cross-language cases are compared and reported so a
/// regression is visible, but nothing is asserted. Forcing English onto Hebrew
/// audio makes both implementations emit different nonsense.
#[test]
#[ignore = "heavy: downloads model weights and runs every model (~10 min first time)"]
fn degenerate_cross_language_cases_are_recorded_only() {
    let mut report = String::new();
    for case in CASES.iter().filter(|case| case.gate == Gate::RecordedOnly) {
        let ours = decoded(case);
        let reference = golden(case);
        let ours_text = joined_text(&ours);
        let reference_text = joined_text(&reference);
        report.push_str(&format!(
            "{:<20} segments {}/{}  text {} vs {} chars  (not gated)\n",
            label(case),
            segments(&ours).len(),
            segments(&reference).len(),
            ours_text.chars().count(),
            reference_text.chars().count(),
        ));
    }
    println!("{report}");
    assert!(!report.is_empty(), "no recorded-only cases configured");
}

/// Guards the fixtures themselves: a renamed or emptied golden would otherwise
/// make the tiers above pass or fail for the wrong reason.
#[test]
fn every_golden_is_present_and_well_formed() {
    for case in CASES {
        let path = golden_path(case);
        let raw = std::fs::read(&path)
            .unwrap_or_else(|e| panic!("missing golden {}: {e}", path.display()));
        let value: serde_json::Value = serde_json::from_slice(&raw).expect("golden parses");

        let mut keys: Vec<&str> = value.as_object().expect("golden is an object").keys().map(String::as_str).collect();
        keys.sort_unstable();
        assert_eq!(keys, ["language", "segments"], "{}: unexpected top-level keys", path.display());

        assert!(value["language"].is_string(), "{}: language must be a string", path.display());
        let segments = segments(&value);
        assert!(!segments.is_empty(), "{}: golden has no segments", path.display());
        for segment in segments {
            let mut keys: Vec<&str> = segment.as_object().expect("segment is an object").keys().map(String::as_str).collect();
            keys.sort_unstable();
            assert_eq!(keys, ["end", "start", "text"], "{}: unexpected segment keys", path.display());
            for field in ["start", "end"] {
                let clock = segment[field].as_str().unwrap_or_else(|| panic!("{} {field} must be a string", path.display()));
                let parts: Vec<&str> = clock.split(':').collect();
                assert_eq!(parts.len(), 2, "{} {field}={clock} is not MM:SS.mmm", path.display());
                assert_eq!(parts[1].split('.').count(), 2, "{} {field}={clock} is not MM:SS.mmm", path.display());
            }
        }

        // Provenance travels with the golden; without it the file cannot be
        // reproduced or invalidated.
        let provenance = golden_dir().join(format!(
            "reference_{}_{}.provenance.json",
            case.model,
            case.language.unwrap_or("auto")
        ));
        assert!(provenance.exists(), "missing provenance for {}", label(case));
    }
}
